### PR TITLE
Prevent premium domains from being sold

### PR DESCRIPTION
**Pull request by winbornejw**
Premium domains are available through NameSilo, but the prices are
different and won't match what package prices are based on.
The NameSilo API returns if a domain is premium or not in the XML
response as an attribute.

### CODE REVIEW

**Comment by JReissmueller** [comment]
This prevent ANY package from selling premium domains.  That seems needlessly restrictive.  It would be better to make this optional based on a package field

**Comment by winbornejw** [comment]
The checkAvailbility() method isn't provided the package. 

I could use some logic similar to that in Blesta's OrderTypeDomain class to get a package that matches, but if someone was to use multiple package groups for domains, I don't know the package group that is appropriate for the order form.

We could make this configurable in the module row meta.

**Comment by JReissmueller** [comment]
Ah, good point, then yes make it an option on the module row and allow their sale by default to maintain backward compatibility

**Comment by JReissmueller** [comment]
No updates appear to be forthcoming from the requester.  This seems like a non-issue since packages already supply a list of supported domains so you can simply exclude the premium domains.

**Comment by winbornejw** [comment]
@JReissmueller I had completely forgot about this until we got bit by it again, sorry about that.

Re-reading the issue, I think there was some misunderstanding on what a premium domain is. You can set the TLDs for packages, but there are premium domains too.

'blesta.club' is not a premium domain and is $10.99 directly from NameSilo: https://www.namesilo.com/domain/search-domains?query=blesta.club

Alternatively, 'lounge.club' is premium and is $906.30 directly from NameSilo: https://www.namesilo.com/domain/search-domains?query=lounge.club

Going further, it was pointed out to me that the NameSilo API doesn't even allow you to purchase premium domains, you have to go through their GUI to actually do it. This results in an order being accepted on our end that the module cannot complete. So I don't think making it optional makes sense and this is just failing more cleanly, since the customers will have to contact the provider regardless.

**Comment by winbornejw** [comment]
Bumping this again to see if there was any thoughts on it.

If you want to keep the current functionality, which seems broken itself, then I can add the module row option as previously discussed.

**Comment by JReissmueller** [comment]
Apologies, I didn't see the response there.  Thank you for the clarification.  I'll try to take a look this week and probably approve it as is based on your explanation.  Thanks!

**Comment by winbornejw** [comment]
Could this be reopened?

**Comment by JReissmueller** [comment]
Apologies, I misread and thought it was merged. I've opened and merged it :)

**Pull request merged**
