### PR TITLE
Improved XML formatting for newer PHP versions

### PR DESCRIPTION
**Pull request by abdyfranco**

### CODE REVIEW

**Comment by nahanil** [comment]
https://3v4l.org/g6b0A

Turns out SimpleXML ain't simple :cry:

I have fears that name server things via the [getDomainInfo](https://www.namesilo.com/api_reference.php#getDomainInfo) API call may also be borked in 7.3.17 but haven't tested IRL https://3v4l.org/argL2

**Comment by abdyfranco** [comment]
> https://3v4l.org/g6b0A
> 
> Turns out SimpleXML ain't simple 😢
> 
> I have fears that name server things via the [getDomainInfo](https://www.namesilo.com/api_reference.php#getDomainInfo) API call may also be borked in 7.3.17 but haven't tested IRL https://3v4l.org/argL2

You have to pass **$simple->reply** instead of **$simple** to **formatResponse()** https://3v4l.org/NWkh0

**Comment by nahanil** [comment]
You sunk my battleship :)

**Comment by nahanil** [comment]
As feared, existing name servers don't show in the admin/client UI with the troublesome PHP version, but do with an earlier one. You can still _update_ them but it'll just show empty boxes when viewing

Before
image

After
image

Sorry for being all Nagatha Christie about this :)

**Comment by abdyfranco** [comment]
> As feared, existing name servers don't show in the admin/client UI with the troublesome PHP version, but do with an earlier one. You can still _update_ them but it'll just show empty boxes when viewing
> 
> Before
> image
> 
> After
> image
> 
> Sorry for being all Nagatha Christie about this :)

I think this time it's finally fixed. :) https://3v4l.org/Nmfrc

**Comment by nahanil** [comment]
By gum you've done it!

Only catch is that with error reporting on (`Configure::errorReporting(-1);`) it chokes on viewing the nameserver managment pages. Availability check doesn't complain.
> "Something went wrong - Undefined property: stdClass::$0"

**Pull request merged**
