### PR TITLE
Fixes issue with incorrect Registrant Verification Status being returned on the UI

### PR DESCRIPTION
**Pull request by julianmatz**
Fixes [NETLINK#44](https://github.com/NETLINK/Blesta-Namesilo/issues/44).
Fixes [NETLINK#47](https://github.com/NETLINK/Blesta-Namesilo/issues/47).
Fixes [NETLINK#49](https://github.com/NETLINK/Blesta-Namesilo/issues/49).

### CODE REVIEW

**Comment by julianmatz** [comment]
Response from `$domains->registrantVerificationStatus()->response()` is as follows. Data is being incorrectly parsed, and verification status is incorrectly showing "Not Verified".
```
array (
  0 =>
  stdClass::__set_state(array(
     '0' =>
    stdClass::__set_state(array(
       'email_address' => 'info@xxxx.xx',
       'domains' => '87',
       'verified' => 'Yes',
    )),
     '1' =>
    stdClass::__set_state(array(
       'email_address' => 'anthony@xxxx.xxx',
       'domains' => '1',
       'verified' => 'No',
    )),
...
```

**Comment by JReissmueller** [comment]
Looks like tab_dnsrecords.pdt should also be updated.

**Review by JReissmueller — CHANGES_REQUESTED** [review]
Looks like tab_dnsrecords.pdt should also be updated.

**Comment by julianmatz** [comment]
Updated.

**Pull request merged**
